In [73]:
import numpy
from enum import Enum
from collections import namedtuple
from scipy import signal
from game import Move
from copy import deepcopy

In [74]:
BOARD_SIZE = (5,5)
mask = numpy.zeros(BOARD_SIZE, dtype=bool)
mask[0, :] = True
mask[-1, :] = True
mask[:, 0] = True
mask[:, -1] = True
board = numpy.ones(BOARD_SIZE, dtype=numpy.uint8) * -1
rboard = numpy.random.randint(-1, 2, BOARD_SIZE, dtype=numpy.int8)
numBoard = numpy.array(range(25)).reshape(5,5)
Slide = namedtuple('Slide', ['roll', 'axis'])


In [75]:
print(numBoard)
def _getNextState(from_pos: tuple[int, int], slide: Move, playerID: int, initialBoard: numpy.ndarray) -> numpy.ndarray:
        board = deepcopy(initialBoard)
        board[from_pos[1], from_pos[0]] = playerID

        if slide == Move.LEFT:
            board[from_pos[1], from_pos[0]:] = numpy.roll(board[from_pos[1], from_pos[0]:], -1)
        elif slide == Move.RIGHT:
            board[from_pos[1], :from_pos[0]+1] = numpy.roll(board[from_pos[1], :from_pos[0]+1], 1)
        elif slide == Move.TOP:
            board[from_pos[1]:, from_pos[0]] = numpy.roll(board[from_pos[1]:, from_pos[0]], -1)
        elif slide == Move.BOTTOM:
            board[:from_pos[1]+1, from_pos[0]] = numpy.roll(board[:from_pos[1]+1, from_pos[0]], 1)
        return board

Coord = (2,4)
slide = Move.RIGHT
player = 100
print(_getNextState(Coord, slide, player, numBoard))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [100  20  21  23  24]]


In [76]:
# def _checkWinner(self, board: numpy.ndarray)-> int:
#     self._

# print(_checkWinner(rboard))

In [78]:
print(rboard)
def __playerWinner(board: numpy.ndarray, playerID: int) -> bool:
    vfboard = board == playerID
    return (numpy.all(vfboard, axis=1).any() or #any row
        numpy.all(vfboard, axis=0).any() or #any col
        numpy.all(numpy.diag(vfboard)) or #main diagonal
        numpy.all(numpy.diag(numpy.fliplr(vfboard)))) #second diagonal

def _checkWinner(self, board: numpy.ndarray)-> int:
    if __playerWinner(board, 1):
        return 1
    if __playerWinner(board, 0):
        return 0
    return -1




[[-1  0  1  1 -1]
 [ 0 -1 -1  0  1]
 [ 0 -1 -1  1 -1]
 [-1  1  0  0  0]
 [ 0  1  0  1  0]]
True


In [79]:

print(float('inf') == float('inf'))

True
